"use client";
import {useEffect,useMemo,useState} from "react";\nimport {track} from "../../../lib/analytics";

type Q={id:number,skill:string,prompt:string,choices:string[],answer:number,why:string};
const questions:Q[]=[
{id:1,skill:"Linear equations",prompt:"Solve 3x + 5 = 20.",choices:["x = 3","x = 5","x = 8","x = 15"],answer:1,why:"Subtract 5, then divide 15 by 3."},
{id:2,skill:"Functions",prompt:"If f(x) = 2x² - 3, what is f(2)?",choices:["1","5","8","13"],answer:1,why:"2(2²) - 3 = 8 - 3 = 5."},
{id:3,skill:"Quadratics",prompt:"Which are the solutions of x² - 5x + 6 = 0?",choices:["2 and 3","-2 and -3","1 and 6","-1 and -6"],answer:0,why:"The expression factors as (x - 2)(x - 3)."},
{id:4,skill:"Exponents",prompt:"Simplify (x³)(x⁴).",choices:["x⁷","x¹²","2x⁷","x"],answer:0,why:"When multiplying like bases, add the exponents: 3 + 4 = 7."},
{id:5,skill:"Quadratics",prompt:"What is the vertex x-coordinate of y = x² - 6x + 5?",choices:["-3","3","5","6"],answer:1,why:"For ax² + bx + c, x = -b/(2a) = 6/2 = 3."},
{id:6,skill:"Functions",prompt:"For g(x) = 3x - 1, which value gives g(x) = 11?",choices:["3","4","5","10/3"],answer:1,why:"Solve 3x - 1 = 11, so 3x = 12 and x = 4."}
];
export default function Diagnostic(){const [answers,setAnswers]=useState<Record<number,number>>({});const [submitted,setSubmitted]=useState(false);useEffect(()=>{track("diagnostic_started")},[]);const result=useMemo(()=>{const skills:Record<string,{right:number,total:number}>={};questions.forEach(q=>{skills[q.skill]??={right:0,total:0};skills[q.skill].total++;if(answers[q.id]===q.answer)skills[q.skill].right++});const correct=questions.filter(q=>answers[q.id]===q.answer).length;const weakest=Object.entries(skills).sort((a,b)=>a[1].right/a[1].total-b[1].right/b[1].total)[0]?.[0];return{correct,skills,weakest}},[answers]);if(submitted)return <main className="page"><div className="eyebrow">DIAGNOSTIC RESULTS · DEMO</div><h1>Your evidence becomes a <em>learning path.</em></h1><p className="lead">You answered {result.correct} of {questions.length} questions correctly. This demonstration uses a simple, inspectable rule rather than a hidden prediction model.</p><section className="results">{Object.entries(result.skills).map(([skill,v])=><div className="result" key={skill}><span>{skill}</span><strong>{Math.round(v.right/v.total*100)}%</strong><div className="bar"><i style={{width:`${v.right/v.total*100}%`}}/></div></div>)}</section><section className="recommend"><small>RECOMMENDED NEXT STEP</small><h2>Review {result.weakest}</h2><p>The demo recommends the lowest-scoring measured skill first. A future classroom release will use a richer prerequisite map and repeated mastery evidence.</p><div className="actions"><a className="button light" href={"/learn/lesson?skill="+({"Linear equations":"linear-equations","Functions":"functions","Quadratics":"quadratics","Exponents":"exponents"}[result.weakest as "Linear equations"|"Functions"|"Quadratics"|"Exponents"]||"linear-equations")}>Start recommended lesson →</a><button onClick={()=>{track("reassessment_started");setAnswers({});setSubmitted(false)}}>Retake diagnostic</button></div></section></main>;return <main className="page"><div className="eyebrow">ALGEBRA II · ANONYMOUS DEMO</div><h1>Find your <em>starting point.</em></h1><p className="lead">Answer six short questions. No name, email, school, or student record is requested. Anonymous product events are recorded to understand how the demo is used.</p><div className="quiz">{questions.map((q,i)=><fieldset key={q.id}><legend><span>0{i+1}</span>{q.prompt}</legend>{q.choices.map((c,j)=><label key={c}><input type="radio" name={`q${q.id}`} checked={answers[q.id]===j} onChange={()=>setAnswers(a=>({...a,[q.id]:j}))}/>{c}</label>)}</fieldset>)}</div><button className="submit" disabled={Object.keys(answers).length!==questions.length} onClick={()=>{track("diagnostic_completed",result.weakest);setSubmitted(true)}}>Build my learning path →</button></main>}