export const dynamic="force-dynamic";
type EventRow={event_type:string;skill:string|null;occurred_at:string;environment:string};
async function loadEvents():Promise<EventRow[]>{
 const raw=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SECRET_KEY;if(!raw||!key)return[];
 const trimmed=raw.endsWith("/")?raw.slice(0,-1):raw;const base=trimmed.endsWith("/rest/v1")?trimmed.slice(0,-8):trimmed;
 const r=await fetch(base+"/rest/v1/learning_events?select=event_type,skill,occurred_at,environment&environment=eq.production&order=occurred_at.desc&limit=500",{headers:{apikey:key,Authorization:"Bearer "+key},cache:"no-store"});
 if(!r.ok)return[];return r.json();
}
const skillLabels:Record<string,string>={"linear-equations":"Linear equations","functions":"Functions","quadratics":"Quadratics","exponents":"Exponents","Linear equations":"Linear equations","Functions":"Functions","Quadratics":"Quadratics","Exponents":"Exponents"};
export default async function Analytics(){const rows=await loadEvents();const count=(e:string)=>rows.filter(r=>r.event_type===e).length;const skills=rows.reduce<Record<string,number>>((a,r)=>{if(r.skill){const label=skillLabels[r.skill]||r.skill;a[label]=(a[label]||0)+1}return a},{});return <main className="page"><div className="eyebrow">AGGREGATE PRODUCT ANALYTICS · EARLY RELEASE</div><h1>Observe usage.<br/><em>Do not overclaim it.</em></h1><p className="lead">These counts summarize anonymous product events recorded on the production site. Preview and development activity is excluded. They do not identify learners and they do not, by themselves, demonstrate learning impact.</p><section className="metricGrid"><article><small>DIAGNOSTICS STARTED</small><strong>{count("diagnostic_started")}</strong></article><article><small>DIAGNOSTICS COMPLETED</small><strong>{count("diagnostic_completed")}</strong></article><article><small>LESSONS OPENED</small><strong>{count("lesson_opened")}</strong></article><article><small>PRACTICE CHECKS</small><strong>{count("practice_checked")}</strong></article></section><section className="lessoncard"><small>SKILL EVENT ACTIVITY</small>{Object.keys(skills).length?Object.entries(skills).sort((a,b)=>b[1]-a[1]).map(([s,n])=><div className="analyticsRow" key={s}><span>{s}</span><strong>{n}</strong></div>):<p>No skill-tagged events yet.</p>}</section><section className="methodCta"><h2>Interpretation matters</h2><p>Development and preview traffic is stored separately and excluded here. Production event counts still represent activity, not unique learners, and should not be interpreted as learning impact without additional evidence.</p><a className="button" href="/impact/methodology">Read the measurement methodology →</a></section></main>}
